import { config } from "dotenv";
config({ path: ".env" });

const {
SUPABASE_URL,
SUPABASE_KEY,
SUPABASE_SERVICE_ROLE_KEY,
TWILIO_ACCOUNT_SID,
TWILIO_AUTH_TOKEN,
TWILIO_PHONE_NUMBER,
PORT
}: any = process.env;

export default {
SUPABASE_URL,
SUPABASE_KEY,
SUPABASE_SERVICE_ROLE_KEY,
TWILIO_ACCOUNT_SID,
TWILIO_AUTH_TOKEN,
TWILIO_PHONE_NUMBER,
PORT
};
